### PR TITLE
Add support for sorting floats

### PR DESCRIPTION
**Pull request by notriddle**
This implementation is ripped out of quickersort, almost verbatim.

### CODE REVIEW

**Comment by stjepang** [comment]
Do you perhaps know whetether someone is using `sort_floats` in the real world? It'd be great to see a concrete situation where it is needed and how exactly it is used.

One thing I find unfortunate is that the function can sort a slice of floats only, and can't e.g. sort arbitrary types by a float key. Can we generalize it?

**Comment by notriddle** [comment]
Sorting by key is possible. The difficult part is maintaining the invariant that a list item doesn't suddenly start claiming to be NaN after the NaN-moving pass is finished.

**Comment by stjepang** [comment]
The following compares floats the same way and is more than 2x faster:

```rust
fn cmp_f64(a: f64, b: f64) -> std::cmp::Ordering {
    fn convert_f64(f: f64) -> u64 {
        let i = unsafe { std::mem::transmute::<f64, u64>(f) };
        let bit = 1 << 63;
        if i & bit == 0 {
            i | bit
        } else {
            !i
        }
    }
    convert_f64(a).cmp(&convert_f64(b))
}
let mut v = vec![0., -0., 7., 5., -3., 1./0., -1./0.];
pdqsort::sort_by(&mut v, |&a, &b| cmp_f64(a, b));
println!("{:?}", v);
```

Output: `[-inf, -3, -0, 0, 5, 7, inf]`

Perhaps we should just provide functions `cmp_f64` and `cmp_f32`?

**Comment by notriddle** [comment]
What does it do with NaNs? (there's more than one NaN bit pattern)

**Comment by notriddle** [comment]
Never mind,

> The IEEE-754 standard defines a NaN as a number with all ones in the exponent, and a non-zero significand. The highest-order bit in the significand specifies whether the NaN is a signaling or quiet one. The remaining bits of the significand form what is referred to as the payload of the NaN.

The exponent is right after the sign bit, and and the all-zero significand is infinity, so NaN will go after infinity.

Now that I know that, yeah let's use it.

**Comment by stjepang** [comment]
NaNs have slightly different behavior...
```rust
let mut v = vec![0., -0., 7., 5., -3., 1./0., -1./0., std::f64::NAN, -std::f64::NAN];
pdqsort::sort_by(&mut v, |&a, &b| cmp_f64(a, b));
println!("{:?}", v);
```
Output: `[NaN, -inf, -3, -0, 0, 5, 7, inf, NaN]`

But if you want all NaNs to come last, you can slightly tweak the function:
```rust
fn cmp_f64(a: f64, b: f64) -> std::cmp::Ordering {
    fn convert_f64(f: f64) -> u64 {
        let u = unsafe { std::mem::transmute::<f64, u64>(f) };
        let sign = 1 << 63;
        let exp = sign - (1 << 52);
        if u & (sign - 1) > exp {
            !0
        } else if u & sign == 0 {
            u | sign
        } else {
            !u
        }
    }
    convert_f64(a).cmp(&convert_f64(b))
}
let mut v = vec![0., -0., 7., 5., -3., 1./0., -1./0., std::f64::NAN, -std::f64::NAN];
pdqsort::sort_by(&mut v, |&a, &b| cmp_f64(a, b));
println!("{:?}", v);
```
Output: `[-inf, -3, -0, 0, 5, 7, inf, NaN, NaN]`

**Comment by stjepang** [comment]
Functions for comparing floats could definitely come in handy, but I feel like they should go into dedicated crates. Let me know if you disagree :)

By the way, I hope to deprecate this crate at some point in the (fairly distant) future. Soon we'll have pdqsort provided by libcore in nightly Rust... [PR](https://github.com/rust-lang/rust/pull/40601)

**Comment by notriddle** [comment]
Yeah, I figured out what it was doing. Doesn't seem like a big problem.

**Comment by notriddle** [comment]
I don't disagree. Float stuff should probably go in a separate crate.

**Comment by stjepang** [comment]
I'm closing this PR, but thanks for the effort!

It'd be great to see the contents of this PR in a separate crate. Comparing floats can definitely be a pain point in Rust. I'm wondering why we don't have something like `f64::raw_cmp` in libcore anyway...

**Comment by notriddle** [comment]
https://crates.io/crates/float-ord

**Pull request closed without merging**
